apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-api-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasks-api
  template:
    metadata:
      labels:
        app: tasks-api
    spec:
      containers:
        - name: task-api-app
          image: tasks-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
