name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # Checks out the code from the repository

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 19.8.1
        # Sets up the Node.js environment with the specified version

      - name: Install dependencies
        run: npm ci
        # Installs project dependencies using npm

      - name: Run unit tests
        run: npm run test
        # Executes the test command to run unit tests

      - name: Copy .env.example to .env
        run: cp .env.example .env
        # Copy .env.example to .env
      - name: Set up MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 6.0
        # Set up MongoDB version 6.0

      - name: Run e2e tests
        run: npm run test:e2e
        # Executes the test command to run e2e tests
